/**
 * 股票大百科题库 —— 内容层（静态数据，零运行时成本）
 * 12 个主题 × 约 150 题，每题：题干 / 选项 / 答案 / 一句话讲解 / 主题·用途·场景三标签 / 难度
 * 玩法层（大百科刷题、K 线小课堂等独立游戏）都从这里取材。
 * 增补题目：按同样结构追加即可；用户出题走线上采纳流程，不直接改这里。
 */

export type EncyclopediaThemeKey =
  | 'kline'
  | 'basics'
  | 'orderTypes'
  | 'indexEtf'
  | 'earnings'
  | 'valuation'
  | 'technicals'
  | 'marketStructure'
  | 'behavior'
  | 'risk'
  | 'usMechanics'
  | 'dividend'

export type EncyclopediaPurpose = 'beginner' | 'intermediate' | 'advanced';

export type EncyclopediaScenario =
  | 'any' | 'premarket' | 'intraday' | 'earnings' | 'crash' | 'sidelined' | 'holding';

export interface EncyclopediaTheme {
  key: EncyclopediaThemeKey;
  name: string;
  emoji: string;
  desc: string;
}

export interface EncyclopediaQuestion {
  id: string;
  theme: EncyclopediaThemeKey;
  purpose: EncyclopediaPurpose;
  scenario: EncyclopediaScenario;
  difficulty: 1 | 2 | 3;
  question: string;
  options: string[];
  /** 正确选项下标；多选题长度 > 1 */
  answer: number[];
  multi: boolean;
  explanation: string;
}

export const ENCYCLOPEDIA_THEMES: EncyclopediaTheme[] = [
  { key: 'kline', name: "K 线形态", emoji: "🕯️", desc: "一根 K 线里藏的多空故事" },
  { key: 'basics', name: "基础概念", emoji: "📖", desc: "蓝筹股市盈率，先把词搞懂" },
  { key: 'orderTypes', name: "买卖机制", emoji: "📝", desc: "市价限价止损，单子怎么挂" },
  { key: 'indexEtf', name: "指数与 ETF", emoji: "📊", desc: "QQQ SPY，一键买下一篮子" },
  { key: 'earnings', name: "财报入门", emoji: "📑", desc: "营收 EPS 指引，财报季不抓瞎" },
  { key: 'valuation', name: "估值指标", emoji: "⚖️", desc: "PE PB PEG，到底贵还是便宜" },
  { key: 'technicals', name: "技术指标", emoji: "📈", desc: "均线 MACD RSI，辅助不算命" },
  { key: 'marketStructure', name: "市场结构", emoji: "🏛️", desc: "牛熊轮动波动率，市场的脾气" },
  { key: 'behavior', name: "交易行为", emoji: "🧠", desc: "拦追高、拦割肉，管住手" },
  { key: 'risk', name: "风险管理", emoji: "🛡️", desc: "仓位止损分散，先活下去" },
  { key: 'usMechanics', name: "美股机制", emoji: "🗽", desc: "T+1 熔断盘前盘后，美股玩法" },
  { key: 'dividend', name: "分红与拆股", emoji: "💰", desc: "股息拆股回购，钱怎么分" },
];

export const ENCYCLOPEDIA_PURPOSE_LABEL: Record<EncyclopediaPurpose, string> = {
  beginner: '新手入门',
  intermediate: '进阶',
  advanced: '实战',
};

export const ENCYCLOPEDIA_SCENARIO_LABEL: Record<EncyclopediaScenario, string> = {
  any: '通用',
  premarket: '开盘前',
  intraday: '盘中',
  earnings: '财报季',
  crash: '大跌时',
  sidelined: '空仓时',
  holding: '持仓中',
};

export const ENCYCLOPEDIA_QUESTIONS: EncyclopediaQuestion[] = [
  {"id": "kline-01", "theme": "kline", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "一根 K 线收盘价高于开盘价，它叫什么？", "options": ["阴线", "阳线", "十字星", "上吊线"], "answer": [1], "multi": false, "explanation": "收盘高于开盘就是阳线，代表这个周期里买方占了上风"},
  {"id": "kline-02", "theme": "kline", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "K 线的上影线特别长，说明盘中发生过什么？", "options": ["一开盘就封死跌停", "全天几乎没有成交", "价格冲高后明显回落", "收盘价等于最低价"], "answer": [2], "multi": false, "explanation": "上影线是从最高价到实体顶端的距离，越长说明上方抛压越重"},
  {"id": "kline-03", "theme": "kline", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "开盘价和收盘价几乎一样，形状像个“十”字，这根 K 线叫？", "options": ["十字星", "锤子线", "光头阳线", "跳空缺口"], "answer": [0], "multi": false, "explanation": "开盘收盘几乎持平就是十字星，代表多空暂时打成平手"},
  {"id": "kline-04", "theme": "kline", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "下跌末端出现一根下影线很长、实体很小的 K 线，它通常叫？", "options": ["上吊线", "十字星", "三只乌鸦", "锤子线"], "answer": [3], "multi": false, "explanation": "长下影线说明被砸下去又被买回来，是常见的止跌信号之一"},
  {"id": "kline-05", "theme": "kline", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "和锤子线长得一模一样，但出现在上涨高位的那根 K 线叫？", "options": ["早晨之星", "上吊线", "光头阴线", "看涨吞没"], "answer": [1], "multi": false, "explanation": "同样形状出现在高位叫上吊线，是上涨动能衰竭的警示信号"},
  {"id": "kline-06", "theme": "kline", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "一根大阳线的实体把前一根小阴线完全包住，这个组合叫？", "options": ["黄昏之星", "早晨之星", "看涨吞没", "十字星"], "answer": [2], "multi": false, "explanation": "后一根实体吞掉前一根，是多头接管的经典看涨组合"},
  {"id": "kline-07", "theme": "kline", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "下跌趋势里依次出现大阴线、小星线、大阳线，这个三根组合是？", "options": ["早晨之星", "黄昏之星", "三只乌鸦", "看跌吞没"], "answer": [0], "multi": false, "explanation": "三根 K 线完成空转多，是教科书级的底部反转组合"},
  {"id": "kline-08", "theme": "kline", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "上涨趋势里依次出现大阳线、小星线、大阴线，这个三根组合是？", "options": ["早晨之星", "看涨吞没", "锤子线", "黄昏之星"], "answer": [3], "multi": false, "explanation": "和早晨之星镜像对应，是经典的顶部反转组合"},
  {"id": "kline-09", "theme": "kline", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "高位连续三根大阴线、每天低开低走，这个组合叫？", "options": ["三个白武士", "三只乌鸦", "早晨之星", "跳空缺口"], "answer": [1], "multi": false, "explanation": "三根阴线步步走低，是空头力量集中的看跌组合"},
  {"id": "kline-10", "theme": "kline", "purpose": "intermediate", "scenario": "premarket", "difficulty": 2, "question": "今天开盘价直接高于昨天最高价，中间留了一段空白，这叫？", "options": ["长上影线", "光头阳线", "跳空缺口", "十字星"], "answer": [2], "multi": false, "explanation": "开盘价跳过昨日价格区间留下的空白，就是跳空缺口"},
  {"id": "kline-11", "theme": "kline", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "没有上下影线，开盘就是最低价、收盘就是最高价的大阳线叫？", "options": ["光头光脚阳线", "T 字线", "锤子线", "十字星"], "answer": [0], "multi": false, "explanation": "没有影线说明一路单边上涨，是多头最强的形态之一"},
  {"id": "kline-12", "theme": "kline", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "以下关于 T 字线和倒 T 字线的说法，正确的有？（多选，共 2 个正确）", "options": ["T 字线一定出现在行情顶部", "T 字线开盘价≈收盘价≈最高价", "倒 T 字线是看涨信号", "倒 T 字线带有很长的上影线"], "answer": [1, 3], "multi": true, "explanation": "T 字线长下影收在高位，倒 T 字线长上影收在低位"},
  {"id": "kline-13", "theme": "kline", "purpose": "advanced", "scenario": "holding", "difficulty": 3, "question": "手里的股票连拉 5 根阳线后，又收出一根长上影线，这时最该警惕什么？", "options": ["肯定还会继续大涨", "成交量已经不重要了", "应该加仓摊高成本", "高位追进去容易站岗"], "answer": [3], "multi": false, "explanation": "连涨后长上影线说明抛压涌现，追高风险明显加大"},
  {"id": "basics-01", "theme": "basics", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "人们常说的蓝筹股，通常指什么样的公司？", "options": ["刚上市的小公司", "股价波动最大的公司", "规模大、经营稳定、常分红的公司", "只涨不跌的公司"], "answer": [2], "multi": false, "explanation": "蓝筹股是大盘绩优股的代称，稳健但不等于只涨不跌"},
  {"id": "basics-02", "theme": "basics", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "成长股和价值股最核心的区别是什么？", "options": ["公司所在的国家不同", "一个看未来增速、一个看当下便宜", "一个分红、一个不分红", "一个在纳斯达克、一个在纽交所"], "answer": [1], "multi": false, "explanation": "成长股买的是高增速，价值股买的是低估值，各有逻辑"},
  {"id": "basics-03", "theme": "basics", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "一家公司的市值是怎么算出来的？", "options": ["净利润乘以市盈率", "总资产减去总负债", "一年的营业收入", "股价乘以总股数"], "answer": [3], "multi": false, "explanation": "市值就是股价乘总股数，代表市场给公司的整体定价"},
  {"id": "basics-04", "theme": "basics", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "市盈率（PE）= 股价 ÷ 每股收益，它主要告诉你什么？", "options": ["为 1 元利润愿意付多少钱", "公司一年能分多少红", "公司欠了多少债", "股价明天涨不涨"], "answer": [0], "multi": false, "explanation": "市盈率是为每 1 元利润付出的价格，越高代表买得越贵"},
  {"id": "basics-05", "theme": "basics", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "市净率（PB）低于 1，通常意味着什么？", "options": ["公司马上要退市", "利润增速一定很高", "股价低于每股净资产", "分红一定很丰厚"], "answer": [2], "multi": false, "explanation": "市净率低于 1 代表股价低于每股净资产，常出现在重资产行业"},
  {"id": "basics-06", "theme": "basics", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "一只股票每年分红 2 美元，现价 50 美元，它的股息率是多少？", "options": ["2%", "4%", "25%", "50%"], "answer": [1], "multi": false, "explanation": "股息率 = 每年分红 ÷ 股价，2 ÷ 50 = 4%"},
  {"id": "basics-07", "theme": "basics", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "流通股数量很少的股票，交易时最容易出现什么情况？", "options": ["永远涨不停", "分红特别高", "不会被做空", "价格波动特别剧烈"], "answer": [3], "multi": false, "explanation": "流通盘小意味着少量资金就能推动价格，波动自然剧烈"},
  {"id": "basics-08", "theme": "basics", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "IPO 指的是什么？", "options": ["公司第一次向公众发行股票", "公司第一次分红", "股票第一次拆股", "公司第一次被收购"], "answer": [0], "multi": false, "explanation": "IPO 就是首次公开募股，公司从此在交易所挂牌交易"},
  {"id": "basics-09", "theme": "basics", "purpose": "advanced", "scenario": "any", "difficulty": 2, "question": "关于股票拆股，以下说法正确的有？（多选，共 2 个正确）", "options": ["1 拆 4 后股价变为原来的四分之一", "拆股后公司市值会翻倍", "拆股会让买入门槛变低、流动性变好", "拆股等于公司多发新股圈钱"], "answer": [0, 2], "multi": true, "explanation": "拆股只切分蛋糕不改变蛋糕大小，市值和股东权益都不变"},
  {"id": "basics-10", "theme": "basics", "purpose": "advanced", "scenario": "earnings", "difficulty": 3, "question": "除息日当天股价开盘比前一天收盘低，最常见的原因是？", "options": ["有人大量抛售", "公司发布了坏消息", "分红的现金已从股价中扣除", "交易所系统出错"], "answer": [2], "multi": false, "explanation": "除息日股价会扣除分红金额，账户里分红现金会补回来"},
  {"id": "basics-11", "theme": "basics", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "指数从低点上涨超过多少，会被叫做技术性牛市？", "options": ["5%", "20%", "50%", "翻倍"], "answer": [1], "multi": false, "explanation": "涨超 20% 叫技术性牛市，跌超 20% 则叫技术性熊市"},
  {"id": "basics-12", "theme": "basics", "purpose": "intermediate", "scenario": "crash", "difficulty": 3, "question": "指数从高点跌了 12%，但还没到熊市标准，这通常被称为什么？", "options": ["牛市加速", "熔断", "黑天鹅", "技术性回调"], "answer": [3], "multi": false, "explanation": "跌 10% 以上叫技术性回调，跌 20% 以上才算技术性熊市"},
  {"id": "basics-13", "theme": "basics", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "1 股并 10 股之后，原来持有 1000 股的股东会变成多少股？", "options": ["100 股", "1000 股不变", "10000 股", "会被强制卖出"], "answer": [0], "multi": false, "explanation": "并股是拆股的反向操作，股数减少、股价同比例提高"},
  {"id": "orderTypes-01", "theme": "orderTypes", "purpose": "beginner", "scenario": "intraday", "difficulty": 1, "question": "你点了市价单买入，它最大的特点是什么？", "options": ["一定按当前显示的价格成交", "马上成交，但成交价可能和看到的不一样", "可以指定价格慢慢等", "只能在盘前盘后使用"], "answer": [1], "multi": false, "explanation": "市价单保证成交速度不保证价格，波动大时容易买贵"},
  {"id": "orderTypes-02", "theme": "orderTypes", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "你想 100 美元买入，但现在股价 105 美元，该用什么单？", "options": ["市价单", "止损单", "盘前市价单", "100 美元的限价买单"], "answer": [3], "multi": false, "explanation": "限价单只按指定价格或更优成交，适合不着急的买入"},
  {"id": "orderTypes-03", "theme": "orderTypes", "purpose": "intermediate", "scenario": "premarket", "difficulty": 2, "question": "为什么盘前盘后交易通常只能用限价单？", "options": ["盘前盘后流动性差，市价单容易以离谱价格成交", "交易所盘前不收市价单手续费", "限价单在盘前成交更快", "盘前只能买不能卖"], "answer": [0], "multi": false, "explanation": "盘前盘后买卖盘稀少，市价单容易滑出很远，限价单更安全"},
  {"id": "orderTypes-04", "theme": "orderTypes", "purpose": "intermediate", "scenario": "holding", "difficulty": 2, "question": "你 50 美元买的股票，挂了 45 美元的止损单，它的作用是？", "options": ["涨到 45 美元自动加仓", "45 美元是你的买入成本", "跌到 45 美元触发卖出、控制亏损", "保证一定按 45 美元成交"], "answer": [2], "multi": false, "explanation": "止损单跌到设定价触发卖出，帮你把亏损控制在计划内"},
  {"id": "orderTypes-05", "theme": "orderTypes", "purpose": "advanced", "scenario": "holding", "difficulty": 3, "question": "股票收盘 45 美元，你挂了 44 美元止损单，隔夜利空开盘 38 美元，你会？", "options": ["按 44 美元卖出", "以 38 美元附近的市价卖出", "止损单自动取消", "按收盘价 45 美元卖出"], "answer": [1], "multi": false, "explanation": "止损单触发后变成市价单，跳空时按开盘附近价格成交"},
  {"id": "orderTypes-06", "theme": "orderTypes", "purpose": "beginner", "scenario": "holding", "difficulty": 1, "question": "股票从 50 美元涨到 70 美元，你想保住利润，该怎么挂单？", "options": ["直接市价全卖掉", "挂 70 美元的买入单", "什么都不做等翻倍", "挂一个 68 美元的限价卖单"], "answer": [3], "multi": false, "explanation": "在现价下方挂限价卖单，跌回来也能保住大部分利润"},
  {"id": "orderTypes-07", "theme": "orderTypes", "purpose": "intermediate", "scenario": "premarket", "difficulty": 2, "question": "美股盘前交易一般从美东时间几点开始？", "options": ["凌晨 4 点", "早上 7 点", "中午 12 点", "晚上 8 点"], "answer": [0], "multi": false, "explanation": "盘前从美东凌晨 4 点到 9 点半，盘后持续到晚上 8 点"},
  {"id": "orderTypes-08", "theme": "orderTypes", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "2024 年 5 月起美股实行 T+1 交收，它的意思是？", "options": ["买入后 1 分钟就能卖", "下单后 1 小时成交", "成交后下一个交易日完成交收", "1 天内必须卖出"], "answer": [2], "multi": false, "explanation": "T+1 指成交后下一个交易日交收，资金到账更快了"},
  {"id": "orderTypes-09", "theme": "orderTypes", "purpose": "intermediate", "scenario": "intraday", "difficulty": 2, "question": "买一价 10.00 美元、卖一价 10.05 美元，这 5 美分的差距叫什么？", "options": ["滑点", "买卖价差", "手续费", "印花税"], "answer": [1], "multi": false, "explanation": "买卖价差是买价和卖价的差，流动性越差价差越大"},
  {"id": "orderTypes-10", "theme": "orderTypes", "purpose": "advanced", "scenario": "intraday", "difficulty": 3, "question": "你看到 100 美元下市价单，最后 100.8 美元成交，多花的 0.8 美元叫？", "options": ["佣金", "价差", "税费", "滑点"], "answer": [3], "multi": false, "explanation": "滑点是预期价格和实际成交价的差，波动大时更常见"},
  {"id": "orderTypes-11", "theme": "orderTypes", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "关于融资（杠杆）交易，以下说法正确的是？", "options": ["涨跌都会被放大，还可能被强制平仓", "只放大收益不放大亏损", "借的钱不用还", "没有任何风险"], "answer": [0], "multi": false, "explanation": "杠杆借钱炒股，涨跌同比例放大，亏多了会被强制平仓"},
  {"id": "orderTypes-12", "theme": "orderTypes", "purpose": "intermediate", "scenario": "intraday", "difficulty": 2, "question": "止损单和止损限价单的核心区别是什么？", "options": ["止损单触发后按市价成交，极端行情下滑点可能很大", "止损限价单触发后一定能按限定价格成交", "两者触发后都保证按止损价成交", "止损单只能在盘后时段使用"], "answer": [0], "multi": false, "explanation": "止损单保触发不保价格；止损限价单加了限价，极端行情可能无法成交。"},
  {"id": "orderTypes-13", "theme": "orderTypes", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "股价 3000 美元的股票，你只有 300 美元，很多券商允许你？", "options": ["只能看着不能买", "必须借钱买一整股", "买 0.1 股碎股", "等它拆股再买"], "answer": [2], "multi": false, "explanation": "碎股让你按金额买入贵价股，0.1 股也能参与"},
  {"id": "indexEtf-01", "theme": "indexEtf", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "纳斯达克综合指数主要包含哪类公司？", "options": ["只有银行股", "只有石油公司", "30 家工业巨头", "以科技股为主的上市公司"], "answer": [3], "multi": false, "explanation": "纳斯达克以科技股闻名，指数覆盖交易所全部上市公司"},
  {"id": "indexEtf-02", "theme": "indexEtf", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "标普 500 指数代表什么？", "options": ["500 家小公司", "美国 500 家大中型上市公司", "500 只科技股", "全球 500 强企业"], "answer": [1], "multi": false, "explanation": "标普 500 覆盖美股 500 家大中型公司，是美股晴雨表"},
  {"id": "indexEtf-03", "theme": "indexEtf", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "道琼斯工业指数由多少只成分股组成？", "options": ["30 只", "100 只", "500 只", "3000 只"], "answer": [0], "multi": false, "explanation": "道指只有 30 只成分股，是历史最悠久的美国股指"},
  {"id": "indexEtf-04", "theme": "indexEtf", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "QQQ 跟踪的是哪个指数？", "options": ["标普 500", "道琼斯工业指数", "纳斯达克 100", "罗素 2000"], "answer": [2], "multi": false, "explanation": "QQQ 跟踪纳斯达克 100 指数，集中了 100 家最大非金融公司"},
  {"id": "indexEtf-05", "theme": "indexEtf", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "想一键买下整个标普 500，最直接的工具是？", "options": ["DIA", "SPY", "QQQ", "VIX"], "answer": [1], "multi": false, "explanation": "SPY 是跟踪标普 500 的 ETF，一份买下 500 家公司"},
  {"id": "indexEtf-06", "theme": "indexEtf", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "DIA 跟踪的是哪个指数？", "options": ["纳斯达克 100", "标普 500", "罗素 2000", "道琼斯工业指数"], "answer": [3], "multi": false, "explanation": "DIA 跟踪道琼斯工业指数，一份买下 30 家成分股"},
  {"id": "indexEtf-07", "theme": "indexEtf", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "ETF 价格能紧贴净值，靠的是什么机制？", "options": ["做市商和机构的申购赎回套利", "证监会每天定价", "基金经理手动调价", "靠持有人投票决定"], "answer": [0], "multi": false, "explanation": "机构用一篮子股票申赎 ETF 份额，套利把价差抹平"},
  {"id": "indexEtf-08", "theme": "indexEtf", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "关于指数基金和主动基金，说法正确的有？（多选，共 2 个正确）", "options": ["指数基金被动跟踪指数，费率通常更低", "主动基金靠基金经理选股，费率通常更高", "指数基金一定跑赢主动基金", "主动基金从不收取管理费"], "answer": [0, 1], "multi": true, "explanation": "指数基金被动跟踪费率低，主动基金靠选股费率高"},
  {"id": "indexEtf-09", "theme": "indexEtf", "purpose": "intermediate", "scenario": "crash", "difficulty": 3, "question": "VIX 被称为恐慌指数，它上涨通常意味着？", "options": ["市场一片乐观", "大家都不交易了", "市场对未来波动的担忧在加剧", "指数一定会大涨"], "answer": [2], "multi": false, "explanation": "VIX 衡量未来 30 天预期波动，飙升代表恐慌情绪蔓延"},
  {"id": "indexEtf-10", "theme": "indexEtf", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "你看好半导体行业但不想赌单只股票，可以买什么？", "options": ["杠杆 ETF", "半导体板块 ETF", "VIX", "国债 ETF"], "answer": [1], "multi": false, "explanation": "板块 ETF 一键买入整个行业，分散单只股票的风险"},
  {"id": "indexEtf-11", "theme": "indexEtf", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "3 倍做多 ETF 长期持有，最大的坑是什么？", "options": ["费率是负的", "涨跌幅和指数完全一样", "只能持有 1 天", "每天重置杠杆，震荡市会被损耗"], "answer": [3], "multi": false, "explanation": "杠杆 ETF 每日重置，长期震荡中复利损耗会吃掉收益"},
  {"id": "indexEtf-12", "theme": "indexEtf", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "ETF 的费率（管理费）越低，对长期持有人意味着什么？", "options": ["每年被扣走的钱越少", "收益一定越高", "分红越多", "风险越小"], "answer": [0], "multi": false, "explanation": "费率是每年从资产里扣的成本，越低长期拖累越小"},
  {"id": "indexEtf-13", "theme": "indexEtf", "purpose": "advanced", "scenario": "sidelined", "difficulty": 3, "question": "同样跟踪标普 500，A 费率 0.03%，B 费率 0.5%，长期持有选哪个更划算？", "options": ["B，因为贵的好", "都一样", "A，费率差会年复一年拉开差距", "看当天谁涨得多"], "answer": [2], "multi": false, "explanation": "跟踪同一指数时，费率是长期回报差距的主要来源"},
  {"id": "earnings-01", "theme": "earnings", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "公司财报里的“营收（Revenue）”指的是什么？", "options": ["公司最终赚到的净利润", "公司卖货或提供服务实际收到的钱", "公司账上的现金余额", "公司发给股东的分红"], "answer": [1], "multi": false, "explanation": "营收是生意进账的总额，扣掉成本费用后才是利润。"},
  {"id": "earnings-02", "theme": "earnings", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "每股收益（EPS）是怎么算出来的？", "options": ["营收除以总股数", "股价除以市盈率", "净利润除以总股数", "分红除以总股数"], "answer": [2], "multi": false, "explanation": "EPS 把利润平摊到每一股，是衡量盈利能力最常用的口径。"},
  {"id": "earnings-03", "theme": "earnings", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "毛利率 60% 说明了什么？", "options": ["卖 100 元货，扣掉直接成本还剩 60 元", "公司净利润是营收的 60%", "公司一年赚了 60% 的收益", "股价一年涨了 60%"], "answer": [0], "multi": false, "explanation": "毛利率只扣直接成本，反映产品本身赚不赚钱、议价能力强不强。"},
  {"id": "earnings-04", "theme": "earnings", "purpose": "intermediate", "scenario": "earnings", "difficulty": 2, "question": "财报电话会里管理层给的“指引（Guidance）”是什么？", "options": ["对股价走势的承诺", "给分析师的买卖建议", "下一季度的分红计划", "对下一季度营收利润的官方预测"], "answer": [3], "multi": false, "explanation": "指引是管理层自己报的下期目标，市场据此修正预期，落空常引发大跌。"},
  {"id": "earnings-05", "theme": "earnings", "purpose": "intermediate", "scenario": "earnings", "difficulty": 2, "question": "公司财报超预期，股价却大跌，最可能的原因是？", "options": ["财报电话会议开得太短", "给出的下季度指引不及预期", "当天成交量太大吓跑了资金", "超预期是利好所以主力借机出货"], "answer": [1], "multi": false, "explanation": "股价看的是未来，指引拉胯等于告诉市场好日子快到头了。"},
  {"id": "earnings-06", "theme": "earnings", "purpose": "beginner", "scenario": "premarket", "difficulty": 1, "question": "美股公司大多选择什么时候发布财报？", "options": ["盘中交易最活跃的时候", "周末休市的时候", "盘前（开盘前）或盘后（收盘后）", "每天收盘集合竞价时段"], "answer": [2], "multi": false, "explanation": "避开交易时段发布，给所有人留出消化信息的时间，避免盘中剧烈波动。"},
  {"id": "earnings-07", "theme": "earnings", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "“营收同比增长 20%，环比下滑 5%”是什么意思？", "options": ["比去年同期多 20%，比上个季度少 5%", "比去年全年多 20%，比上月少 5%", "比上市时多 20%，比昨天少 5%", "比预期高 20%，比指引低 5%"], "answer": [0], "multi": false, "explanation": "同比看长期趋势，环比看最近动能，两者结合才看得全。"},
  {"id": "earnings-08", "theme": "earnings", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "自由现金流（Free Cash Flow）为什么常被说比净利润更“实在”？", "options": ["它永远比净利润数字更大", "它只统计海外业务的现金", "它不需要看财报就能算出来", "它是真金白银的现金流入，会计腾挪空间小"], "answer": [3], "multi": false, "explanation": "净利润可以靠会计手法调节，自由现金流是实打实进兜的钱。"},
  {"id": "earnings-09", "theme": "earnings", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "科技公司研发费用占营收比很高，财报上通常意味着什么？", "options": ["公司一定在浪费钱", "利润被压低，等于在为未来增长下注", "研发费用可以直接变成现金", "高研发等于高分红能力"], "answer": [1], "multi": false, "explanation": "研发当期全进费用拉低利润，值不值要看未来产品能不能兑现。"},
  {"id": "earnings-10", "theme": "earnings", "purpose": "beginner", "scenario": "earnings", "difficulty": 2, "question": "美股财报季一般集中在哪几个月？", "options": ["3 月、6 月、9 月、12 月", "2 月、5 月、8 月、11 月", "1 月、4 月、7 月、10 月", "每个月都一样多"], "answer": [2], "multi": false, "explanation": "多数公司季度在 3/6/9/12 月结束，财报在次月密集发布。"},
  {"id": "earnings-11", "theme": "earnings", "purpose": "intermediate", "scenario": "earnings", "difficulty": 2, "question": "财报电话会议（Earnings Call）上最值得听的是哪个环节？", "options": ["分析师提问环节，管理层回答藏着真实预期", "开场念稿的营收数字", "主持人的开场白", "会议结束时的感谢词"], "answer": [0], "multi": false, "explanation": "念稿都是写好的，问答环节的迟疑和措辞才暴露管理层真正的底气。"},
  {"id": "earnings-12", "theme": "earnings", "purpose": "intermediate", "scenario": "premarket", "difficulty": 3, "question": "想提前知道某只美股哪天盘前发布财报，最靠谱的做法是？", "options": ["看股吧里网友的爆料", "等当天开盘看股价异动", "问券商客服哪天发财报", "去 Nasdaq 官网或券商 App 查财报日历"], "answer": [3], "multi": false, "explanation": "交易所官网和券商财报日历是官方信源，日期准还标注盘前盘后。"},
  {"id": "earnings-13", "theme": "earnings", "purpose": "advanced", "scenario": "earnings", "difficulty": 3, "question": "财报超预期但股价下跌，可能的原因有哪些？（多选，共 2 个正确）", "options": ["超预期意味着公司不再增长", "下季度指引不及预期", "财报超预期所以散户都赚钱了", "市场此前预期更高，利好已提前兑现"], "answer": [1, 3], "multi": true, "explanation": "股价反映的是预期差：指引拉胯或利好提前透支，都会让好财报变砸盘。"},
  {"id": "valuation-01", "theme": "valuation", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "市盈率（PE）= 50，通俗理解是什么？", "options": ["公司每年分红 50%", "股价 50 天翻一倍", "按现在盈利水平，50 年才能赚回股价", "公司有 50 倍现金"], "answer": [2], "multi": false, "explanation": "PE 是“回本年限”的粗估：越高，市场为每块钱利润付的价越高。"},
  {"id": "valuation-02", "theme": "valuation", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "动态市盈率和静态市盈率的区别是？", "options": ["动态用未来预期盈利算，静态用过去已实现盈利算", "动态每天变、静态一年变一次", "动态只用于美股、静态只用于 A 股", "动态是估值、静态是技术指标"], "answer": [0], "multi": false, "explanation": "静态看过去，动态看未来预期，成长股多看动态。"},
  {"id": "valuation-03", "theme": "valuation", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "市净率（PB）= 1 意味着什么？", "options": ["公司净资产是股价的一倍", "公司账上现金等于市值", "股价一年没涨过", "股价刚好等于每股净资产"], "answer": [3], "multi": false, "explanation": "PB 是股价相对净资产的倍数，=1 就是按账面净资产卖你。"},
  {"id": "valuation-04", "theme": "valuation", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "公司还没盈利，看估值一般不用 PE，而用？", "options": ["市净率（PB）", "市销率（PS）：市值除以营收", "股息率", "换手率"], "answer": [1], "multi": false, "explanation": "没利润时 PE 失效，PS 看市场为每块钱营收付多少钱，适合早期成长股。"},
  {"id": "valuation-05", "theme": "valuation", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "PEG = 0.8 通常被解读为？", "options": ["估值偏贵、要小心", "公司增长停滞了", "相对增速而言估值偏便宜", "股息太低不值得买"], "answer": [2], "multi": false, "explanation": "PEG = PE 除以增速，小于 1 常被视为“增长没被充分定价”。"},
  {"id": "valuation-06", "theme": "valuation", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "成长股 PE 动辄 50 倍以上，市场逻辑是什么？", "options": ["在为未来的高速增长提前付费，赌盈利会跟上来", "PE 高代表公司现在很赚钱", "高 PE 的股票波动小更安全", "PE 越高分红越多"], "answer": [0], "multi": false, "explanation": "高 PE 是把未来增长折成今天的价格，增长兑现不了就会杀估值。"},
  {"id": "valuation-07", "theme": "valuation", "purpose": "advanced", "scenario": "crash", "difficulty": 3, "question": "周期股在行业景气顶峰时，PE 看起来很低，这时要警惕什么？", "options": ["PE 低说明一定值得抄底", "周期股 PE 低是因为分红高", "低 PE 周期股没有风险", "盈利是周期高点，不可持续，低 PE 是陷阱"], "answer": [3], "multi": false, "explanation": "周期股要在 PE 高（盈利谷底）时看便宜，PE 最低时往往是周期顶点。"},
  {"id": "valuation-08", "theme": "valuation", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "“相对估值”和“绝对估值”的区别是？", "options": ["相对估值看过去、绝对估值看未来", "相对估值跟同行比，绝对估值算公司自己值多少钱", "相对估值是技术分析、绝对估值是基本面", "两者没有区别"], "answer": [1], "multi": false, "explanation": "相对估值问“贵不贵（跟同行比）”，绝对估值问“值多少（现金流折现）”。"},
  {"id": "valuation-09", "theme": "valuation", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "企业价值（EV）比市值多考虑了什么？", "options": ["加上员工人数", "减去无形资产", "加上有息负债、减去现金，反映真实收购成本", "加上未来十年的利润"], "answer": [2], "multi": false, "explanation": "收购一家公司要承接它的债、拿到它的现金，EV 才是完整价格。"},
  {"id": "valuation-10", "theme": "valuation", "purpose": "intermediate", "scenario": "holding", "difficulty": 2, "question": "分析师给目标价 180–220 美元，这说明了什么估值观？", "options": ["估值是区间不是精确的点，留有容错空间", "分析师算不准所以给两个数", "股价一定会在 180 到 220 之间", "目标价越宽越不专业"], "answer": [0], "multi": false, "explanation": "估值依赖假设，假设一变结论就变，给区间是诚实的做法。"},
  {"id": "valuation-11", "theme": "valuation", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "“股息贴现”这个估值思路，核心直觉是什么？", "options": ["分红越多的公司股价越高", "贴现就是打折买股票", "股息是固定的所以估值很准", "股票值多少钱，取决于未来能分到多少现金"], "answer": [3], "multi": false, "explanation": "买股票等于买未来现金流，分红稳定的公司适合这么算。"},
  {"id": "valuation-12", "theme": "valuation", "purpose": "advanced", "scenario": "crash", "difficulty": 3, "question": "哪些情况下市盈率（PE）会失效或误导？（多选，共 2 个正确）", "options": ["公司亏损，PE 为负无意义", "PE 超过 100 倍", "周期顶峰盈利虚高，PE 显得很便宜", "公司刚分过红"], "answer": [0, 2], "multi": true, "explanation": "亏损让 PE 无意义，周期高点让 PE 虚低，这两种情况都要换指标看。"},
  {"id": "valuation-13", "theme": "valuation", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "现金流折现（DCF）估值法，一句话直觉是什么？", "options": ["看过去十年股价平均值", "把公司未来能赚的现金折成今天的钱加总", "现金流越多估值公式越复杂", "DCF 只适用于银行股"], "answer": [1], "multi": false, "explanation": "未来的钱不如今天的钱值钱，折现就是把时间差换算成价格差。"},
  {"id": "technicals-01", "theme": "technicals", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "MA20（20 日均线）代表什么？", "options": ["未来 20 天的预测股价", "过去 20 个交易日收盘价的平均成本线", "20 天内最高价和最低价的中点", "20 家机构的平均目标价"], "answer": [1], "multi": false, "explanation": "均线是市场平均持仓成本，价格在均线上方意味着多数人赚钱。"},
  {"id": "technicals-02", "theme": "technicals", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "短期均线上穿长期均线，被称作什么？", "options": ["死叉，常被视为走弱信号", "背离，说明趋势要反转", "钝化，说明指标失效", "金叉，常被视为走强信号"], "answer": [3], "multi": false, "explanation": "金叉代表短期成本超过长期成本，是多头排列的起点，但只是辅助信号。"},
  {"id": "technicals-03", "theme": "technicals", "purpose": "intermediate", "scenario": "intraday", "difficulty": 2, "question": "MACD 的柱状图（红绿柱）变长，说明什么？", "options": ["多空力量的差距在拉大，趋势在加速", "股价一定会继续涨", "成交量在放大", "市场要反转了"], "answer": [0], "multi": false, "explanation": "红绿柱是快慢线差值的可视化，变长=动能增强，缩短=动能衰减。"},
  {"id": "technicals-04", "theme": "technicals", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "RSI（相对强弱指数）冲到 85，按经典用法意味着？", "options": ["买入信号强烈", "市场没有风险了", "进入超买区，追高要谨慎", "股价会立刻跌 85%"], "answer": [2], "multi": false, "explanation": "RSI 超过 70 是传统超买线，提示涨多了，但强趋势里可以一直钝化。"},
  {"id": "technicals-05", "theme": "technicals", "purpose": "intermediate", "scenario": "intraday", "difficulty": 2, "question": "KDJ 指标里，K 线上穿 D 线通常被称作？", "options": ["死叉，视为走弱信号", "金叉，视为短期走强信号", "背离，趋势要反转", "共振，可以满仓"], "answer": [1], "multi": false, "explanation": "KDJ 对价格敏感、变化快，适合看短期节奏，震荡市比趋势市好用。"},
  {"id": "technicals-06", "theme": "technicals", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "布林带（BOLL）默认是 20 日均线上下各加减几倍标准差？", "options": ["1 倍", "3 倍", "0.5 倍", "2 倍"], "answer": [3], "multi": false, "explanation": "默认参数 20 日均线 ±2 倍标准差，股价触及上下轨常被视为超买超卖。"},
  {"id": "technicals-07", "theme": "technicals", "purpose": "advanced", "scenario": "intraday", "difficulty": 3, "question": "盘中股价创新高但成交量明显萎缩，技术派一般怎么看？", "options": ["上涨动能不足，追高要谨慎", "缩量上涨更健康可以追", "成交量不重要", "一定是主力在洗盘"], "answer": [0], "multi": false, "explanation": "健康的上涨需要量能配合，价涨量缩是典型的量价背离预警。"},
  {"id": "technicals-08", "theme": "technicals", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "“顶背离”指的是哪种量价/指标组合？", "options": ["股价新低但成交量放大", "均线金叉但股价下跌", "股价新高但指标（MACD/RSI）没跟上新高", "布林带收口但股价横盘"], "answer": [2], "multi": false, "explanation": "价格创新高而动能指标不创新高，说明上涨后劲不足，是常见见顶信号之一。"},
  {"id": "technicals-09", "theme": "technicals", "purpose": "intermediate", "scenario": "holding", "difficulty": 2, "question": "股价跌到前期低点附近又弹起来，这个前期低点被称作？", "options": ["阻力位：抛压集中的位置", "支撑位：买盘可能再次承接的位置", "止损位：必须卖出的位置", "成本位：主力的建仓价"], "answer": [1], "multi": false, "explanation": "支撑是“上次有人在这里买”留下的记忆，跌破就反转为阻力。"},
  {"id": "technicals-10", "theme": "technicals", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "上升趋势线一般怎么画？", "options": ["连接两个高点向右下方延伸", "穿过 K 线实体中间画横线", "随便画一条斜线", "连接两个以上的阶段性低点，向右上方延伸"], "answer": [3], "multi": false, "explanation": "趋势线连接低点托住上涨，跌破趋势线常被视为趋势走弱。"},
  {"id": "technicals-11", "theme": "technicals", "purpose": "intermediate", "scenario": "holding", "difficulty": 2, "question": "乖离率（BIAS）为 +15%，说明什么？", "options": ["股价偏离均线 15%，偏离过大有回调压力", "股价比昨天涨了 15%", "均线比股价高 15%", "市场情绪偏离理性 15%"], "answer": [0], "multi": false, "explanation": "乖离率衡量股价离均线有多远，离太远总有向均线回归的引力。"},
  {"id": "technicals-12", "theme": "technicals", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "强势上涨中 RSI 连续一周待在 80 以上，这叫什么现象？", "options": ["指标失灵：RSI 坏了", "顶背离：马上要大跌", "指标钝化：强趋势下超买信号会长期失效", "金叉：赶紧加仓"], "answer": [2], "multi": false, "explanation": "单边趋势里指标会“赖在”超买超卖区不出来，逆着做容易被碾压。"},
  {"id": "technicals-13", "theme": "technicals", "purpose": "intermediate", "scenario": "any", "difficulty": 3, "question": "以下哪些属于趋势类指标？（多选，共 2 个正确）", "options": ["RSI", "均线（MA）", "KDJ", "MACD"], "answer": [1, 3], "multi": true, "explanation": "均线和 MACD 跟趋势走，RSI 和 KDJ 是摆动类，看超买超卖。"},
  {"id": "marketStructure-01", "theme": "marketStructure", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "美股常说的“技术性熊市”一般指什么？", "options": ["连跌 20 天", "20% 的股票跌停", "指数从高点下跌超过 20%", "成交量萎缩 20%"], "answer": [2], "multi": false, "explanation": "跌超 20% 是公认的技术性熊市线，反弹超 20% 则常被称为技术性牛市。"},
  {"id": "marketStructure-02", "theme": "marketStructure", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "“板块轮动”是什么意思？", "options": ["资金在不同行业板块之间来回切换领涨", "股票每天轮流停牌", "指数成分股定期更换", "板块每天轮流涨停"], "answer": [0], "multi": false, "explanation": "经济周期不同阶段领涨板块不同，踏不准轮动容易两边挨打。"},
  {"id": "marketStructure-03", "theme": "marketStructure", "purpose": "intermediate", "scenario": "crash", "difficulty": 2, "question": "VIX 被称为“恐慌指数”，它涨到 40 意味着？", "options": ["市场很平静没人交易", "未来 40 天一定大涨", "指数要涨 40%", "市场预期未来波动剧烈，恐慌情绪浓"], "answer": [3], "multi": false, "explanation": "VIX 衡量标普 500 期权隐含波动率，越高代表市场越害怕。"},
  {"id": "marketStructure-04", "theme": "marketStructure", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "一只股票“流动性好”是什么意思？", "options": ["公司账上现金多", "买卖盘充足，想买买得到、想卖卖得掉", "股价波动很小", "分红特别多"], "answer": [1], "multi": false, "explanation": "流动性好=交易不愁对手盘，大资金进出不至于把价格砸出坑。"},
  {"id": "marketStructure-05", "theme": "marketStructure", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "美股做市商（Market Maker）的核心工作是？", "options": ["替散户决定买卖", "保证股价只涨不跌", "持续报出买卖价，为市场提供流动性", "给上市公司做宣传"], "answer": [2], "multi": false, "explanation": "做市商靠买卖价差赚钱，他们的存在让你的单子随时有人接。"},
  {"id": "marketStructure-06", "theme": "marketStructure", "purpose": "intermediate", "scenario": "crash", "difficulty": 2, "question": "美股标普 500 指数日内跌 7% 会触发什么？", "options": ["全市场熔断停牌 15 分钟", "直接收盘不再交易", "只停牌成分股", "什么都不发生"], "answer": [0], "multi": false, "explanation": "7% 和 13% 熔断 15 分钟，20% 直接全天停牌。"},
  {"id": "marketStructure-07", "theme": "marketStructure", "purpose": "intermediate", "scenario": "intraday", "difficulty": 2, "question": "美股盘中突然停牌（Trading Halt），最常见的原因是？", "options": ["公司倒闭了", "股价涨太多被强制停牌", "系统出故障了", "有重大消息待公布，交易所暂停交易防不公平"], "answer": [3], "multi": false, "explanation": "待消息公布时停牌是让所有人同时看到消息，复牌后常伴随剧烈波动。"},
  {"id": "marketStructure-08", "theme": "marketStructure", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "盘后出现一笔远低于收盘价的大宗成交，说明了什么？", "options": ["公司基本面出问题了", "有机构在场外协商转让，大单折价是常态", "明天一定低开", "是散户的大单"], "answer": [1], "multi": false, "explanation": "大宗交易（Block Trade）是机构间协商价，折价成交不代表市场价变了。"},
  {"id": "marketStructure-09", "theme": "marketStructure", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "美股没有“北向资金”，看机构动向一般看什么？", "options": ["每天的龙虎榜", "交易所的席位数据", "13F 报告：大机构每季度披露的持仓", "股吧大 V 的持仓晒单"], "answer": [2], "multi": false, "explanation": "管钱超 1 亿美元的机构每季末 45 天内披露持仓，是公开的机构风向标。"},
  {"id": "marketStructure-10", "theme": "marketStructure", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "指数在涨，但上涨家数远少于下跌家数，这说明？", "options": ["涨指数不涨个股，靠少数权重股硬撑", "市场非常健康", "下跌家数不重要", "牛市来了"], "answer": [0], "multi": false, "explanation": "涨跌家数是市场广度，只看指数会被“虚胖”的指数骗了。"},
  {"id": "marketStructure-11", "theme": "marketStructure", "purpose": "beginner", "scenario": "crash", "difficulty": 1, "question": "VIX 长期均值大约在什么位置？", "options": ["5 附近", "50 附近", "100 附近", "20 附近"], "answer": [3], "multi": false, "explanation": "VIX 均值约 20，30 以上算恐慌，12 以下算极度平静。"},
  {"id": "marketStructure-12", "theme": "marketStructure", "purpose": "intermediate", "scenario": "intraday", "difficulty": 3, "question": "缩量上涨和放量上涨，技术派更信任哪个？", "options": ["缩量上涨：抛压小更轻松", "放量上涨：有真金白银的买盘在推", "都一样", "看心情"], "answer": [1], "multi": false, "explanation": "放量代表分歧中买方胜出，缩量上涨遇到抛压容易一日游。"},
  {"id": "marketStructure-13", "theme": "marketStructure", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "以下哪些是典型牛市特征？（多选，共 2 个正确）", "options": ["指数不断新高，回调幅度浅", "所有股票每天都涨", "成交量持续萎缩", "每次下跌都被迅速买回"], "answer": [0, 3], "multi": true, "explanation": "牛市=新高不断+回调买盘强，普涨和缩量都不是牛市的必要条件。"},
  {"id": "behavior-01", "theme": "behavior", "purpose": "beginner", "scenario": "intraday", "difficulty": 1, "question": "看到一只股票盘中大涨 8%，手痒想追进去，动手前最该先问自己什么？", "options": ["它还能再涨几个板", "我追进去的理由是什么，跌了怎么办", "论坛里大家都在喊买入吗", "涨得越多越安全，赶紧买"], "answer": [1], "multi": false, "explanation": "追高前先想好退出条件，没计划的追高就是赌博。"},
  {"id": "behavior-02", "theme": "behavior", "purpose": "beginner", "scenario": "holding", "difficulty": 1, "question": "账面浮亏 15% 时，最常见的错误心态是？", "options": ["按原计划执行止损", "重新评估买入逻辑是否还在", "越跌越觉得“卖了就真亏了”，死扛到底", "先卖一半降低仓位"], "answer": [2], "multi": false, "explanation": "浮亏变实亏只是心理安慰，死扛让小亏变大亏。"},
  {"id": "behavior-03", "theme": "behavior", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "定投最大的好处是什么？", "options": ["保证每次都买在最低点", "分散买入时点，平滑成本，减少择时焦虑", "牛市里收益一定超过梭哈", "不用选股票，随便买都行"], "answer": [1], "multi": false, "explanation": "定投赢在纪律，用时间分散替代猜点位。"},
  {"id": "behavior-04", "theme": "behavior", "purpose": "intermediate", "scenario": "sidelined", "difficulty": 2, "question": "把全部资金一次投入一只股票（梭哈），最大的风险是？", "options": ["券商手续费太高", "涨得太快来不及加仓", "分红到账太慢", "一次押错就没有翻身资金，心态直接崩"], "answer": [3], "multi": false, "explanation": "梭哈把容错率压到零，一次失误就出局。"},
  {"id": "behavior-05", "theme": "behavior", "purpose": "intermediate", "scenario": "crash", "difficulty": 2, "question": "大跌时总想“抄底”，更稳妥的做法是？", "options": ["跌 10% 就全仓抄，一把翻身", "分批买入，每批设好止损，越跌买得越谨慎", "等反弹 5% 再追，更安全", "抄底全看运气，凭感觉就行"], "answer": [1], "multi": false, "explanation": "没人知道底在哪，分批加止损才是抄底的正确姿势。"},
  {"id": "behavior-06", "theme": "behavior", "purpose": "intermediate", "scenario": "holding", "difficulty": 2, "question": "“补仓”和“加仓”的本质区别是？", "options": ["补仓是亏钱后加，加仓是赚钱后加", "补仓金额大，加仓金额小", "补仓只能补一次，加仓可以多次", "没有区别，都是买入"], "answer": [0], "multi": false, "explanation": "亏钱补仓是摊低成本的自救，赚钱加仓是顺势扩大战果，心态完全不同。"},
  {"id": "behavior-07", "theme": "behavior", "purpose": "intermediate", "scenario": "holding", "difficulty": 2, "question": "刚涨 10% 就卖了，结果之后翻倍，这种“卖飞”通常是因为？", "options": ["运气不好，卖早了", "卖出手续费太贵", "买入时没想好持有逻辑，涨一点就心慌落袋", "应该永远不卖"], "answer": [2], "multi": false, "explanation": "拿不住的根因是买入时没答案，涨跌都成了惊吓。"},
  {"id": "behavior-08", "theme": "behavior", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "频繁买卖最大的隐形成本是？", "options": ["手机电量消耗快", "手续费和价差不断侵蚀本金，还总买在情绪高点", "券商会打电话骚扰", "账户会被强制销户"], "answer": [1], "multi": false, "explanation": "每次交易都在交税给市场，频繁交易者多半在为情绪买单。"},
  {"id": "behavior-09", "theme": "behavior", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "看到所有人都在买某只股票时，最该警惕的是？", "options": ["自己买得比别人晚", "券商服务器会卡", "买的人多一定更安全", "人人都知道的好消息，价格里多半已经反映了"], "answer": [3], "multi": false, "explanation": "共识形成时往往是价格高点，追人多的地方最容易接盘。"},
  {"id": "behavior-10", "theme": "behavior", "purpose": "intermediate", "scenario": "holding", "difficulty": 2, "question": "总盯着自己的成本价做买卖决策，这是哪种心理陷阱？", "options": ["锚定效应：成本价只是你的历史，与股票未来无关", "羊群效应", "幸存者偏差", "这是理性行为，没有陷阱"], "answer": [0], "multi": false, "explanation": "成本价是沉没成本，该看的是未来，不是过去。"},
  {"id": "behavior-11", "theme": "behavior", "purpose": "advanced", "scenario": "holding", "difficulty": 3, "question": "人们面对亏损和盈利时，最常见的两种反应是？（多选，共 2 个正确）", "options": ["亏钱的股票舍不得卖，赚钱的股票急着落袋", "亏损时更愿意冒险扛着，盈利时反而保守", "盈亏都无所谓，完全理性", "亏损时果断止损，盈利时耐心持有"], "answer": [0, 1], "multi": true, "explanation": "损失厌恶让人“截断利润、放任亏损”，正好和赚钱反着来。"},
  {"id": "behavior-12", "theme": "behavior", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "同样 10 年，为什么追涨杀跌的人多半跑输“拿住不动”的人？", "options": ["因为拿住不动的人运气更好", "因为市场只奖励长期投资者", "追涨杀跌把“低买高卖”做成了“高买低卖”，还不断交手续费", "追涨杀跌的人本金更少"], "answer": [2], "multi": false, "explanation": "频繁择时等于系统性地在高点买、低点卖，复利被自己玩没了。"},
  {"id": "risk-01", "theme": "risk", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "仓位管理最核心的一句话是？", "options": ["看好的股票就该全仓", "仓位越重赚得越快", "任何单笔亏损都不应伤筋动骨，活下去才有下一局", "满仓才能跑赢通胀"], "answer": [2], "multi": false, "explanation": "仓位管理的本质是控制单次犯错的代价。"},
  {"id": "risk-02", "theme": "risk", "purpose": "beginner", "scenario": "holding", "difficulty": 1, "question": "设止损的真正作用是？", "options": ["保证每次交易都赚钱", "跌破预设位置自动离场，把亏损锁在计划内", "让券商多收手续费", "防止股票涨得太快"], "answer": [1], "multi": false, "explanation": "止损不是认输，是给每笔交易买保险。"},
  {"id": "risk-03", "theme": "risk", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "分散投资能分散掉什么？", "options": ["所有风险，包括大盘暴跌", "个股的特有风险，但分散不掉系统性风险", "手续费", "什么都分散不掉，纯属心理安慰"], "answer": [1], "multi": false, "explanation": "分散防的是“单只爆雷”，防不住整个市场一起跌。"},
  {"id": "risk-04", "theme": "risk", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "普通投资者单只股票仓位比较稳妥的上限直觉是？", "options": ["不超过总资金的 10%–20%，一只亏光也不致命", "50%，看好就要下重注", "100%，集中火力", "越少越好，1% 最安全"], "answer": [0], "multi": false, "explanation": "单只仓位设上限，是防止一次看走眼就出局。"},
  {"id": "risk-05", "theme": "risk", "purpose": "intermediate", "scenario": "holding", "difficulty": 2, "question": "账户从高点跌了 20%（回撤 20%），要回到原点需要涨多少？", "options": ["涨 20% 就回来了", "需要涨 25%", "需要涨 30%", "涨 15% 就够了"], "answer": [1], "multi": false, "explanation": "亏 20% 后只剩 8 成，回本需要涨 25%，亏损越深回本越难。"},
  {"id": "risk-06", "theme": "risk", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "一笔交易潜在盈利 3 元、潜在亏损 1 元，这个风险收益比意味着？", "options": ["风险太大，不能做", "风险和收益差不多，无所谓", "无法计算", "亏 1 块博 3 块，值得做"], "answer": [3], "multi": false, "explanation": "风险收益比看的是“亏小博大”，赢一次能覆盖输三次。"},
  {"id": "risk-07", "theme": "risk", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "凯利公式给普通人的最大启示是？", "options": ["胜率越高越该全仓", "即使胜算大，也别重仓押注，留余地才能穿越运气波动", "公式太复杂，散户用不上", "应该借钱加杠杆"], "answer": [1], "multi": false, "explanation": "凯利公式的精髓是“有优势也别押上全部”，活着比赢一次重要。"},
  {"id": "risk-08", "theme": "risk", "purpose": "advanced", "scenario": "crash", "difficulty": 3, "question": "“黑天鹅”事件对投资者的真正教训是？", "options": ["努力预测下一次黑天鹅", "承认无法预测，靠仓位和止损让任何一次意外都杀不死你", "黑天鹅之后再也不买股票", "黑天鹅只影响别人"], "answer": [1], "multi": false, "explanation": "黑天鹅防不住，只能让自己“被砸中也不死”。"},
  {"id": "risk-09", "theme": "risk", "purpose": "intermediate", "scenario": "holding", "difficulty": 2, "question": "收到券商的保证金追缴通知（margin call）意味着？", "options": ["券商送你一笔奖金", "可以免费加杠杆", "账户跌破维持保证金要求，必须加钱或被强制平仓", "只是系统提醒，不用理会"], "answer": [2], "multi": false, "explanation": "margin call 是最后通牒，不补钱券商就替你割肉。"},
  {"id": "risk-10", "theme": "risk", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "为什么总说“用闲钱投资”？", "options": ["闲钱亏了不心疼，可以随便买", "短期要用的钱一旦被套，被迫在低点卖出，亏损变现实", "闲钱收益更高", "这是券商的营销话术"], "answer": [1], "multi": false, "explanation": "拿急用的钱炒股，时间会逼你在最差的时机卖出。"},
  {"id": "risk-11", "theme": "risk", "purpose": "advanced", "scenario": "holding", "difficulty": 3, "question": "设了止损但每次都“再等等”不执行，结果通常是？", "options": ["多等等总能涨回来", "小亏拖成大亏，止损形同虚设，还不如不设", "说明止损设得太紧", "锻炼了耐心，是好事"], "answer": [1], "multi": false, "explanation": "不执行的止损等于没有，纪律的价值全在执行那一刻。"},
  {"id": "risk-12", "theme": "risk", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "以下哪些算“对冲”的思路？（多选，共 2 个正确）", "options": ["持有股票的同时，配置一部分债券或现金", "把所有钱都换成同一板块的龙头", "做多看好的行业，同时回避高度相关的风险敞口", "跌了就加倍补仓摊低成本"], "answer": [0, 2], "multi": true, "explanation": "对冲是“东边不亮西边亮”，不是把鸡蛋换个篮子装。"},
  {"id": "usMechanics-01", "theme": "usMechanics", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "美股现在实行 T+1 交收，它是什么意思？", "options": ["买入后 1 分钟就能卖出", "交易日之后 1 个工作日内完成钱券交割", "每天只能交易 1 次", "持股必须满 1 天"], "answer": [1], "multi": false, "explanation": "T+1 指交割结算周期，2024 年 5 月 28 日起由 T+2 缩短而来。"},
  {"id": "usMechanics-02", "theme": "usMechanics", "purpose": "beginner", "scenario": "crash", "difficulty": 1, "question": "美股熔断看哪个指数、触发点位是？", "options": ["看道指，跌 5% 熔断", "只看标普 500，跌 7%/13%/20% 分三档触发", "看纳指，跌 10% 熔断", "三大指数任一达标就熔断"], "answer": [1], "multi": false, "explanation": "熔断唯一标尺是标普 500，三档 7%/13%/20%，只熔下跌不熔上涨。"},
  {"id": "usMechanics-03", "theme": "usMechanics", "purpose": "intermediate", "scenario": "intraday", "difficulty": 2, "question": "美股个股单日涨跌幅有限制吗？", "options": ["有 10% 涨跌停，和 A 股一样", "完全没限制，想怎么波动都行", "没有固定涨跌停，但剧烈波动会触发 LULD 暂停交易 5 分钟冷静", "涨不限，跌限 10%"], "answer": [2], "multi": false, "explanation": "美股没有涨跌停板，极端波动靠 LULD 个股暂停 5 分钟缓冲。"},
  {"id": "usMechanics-04", "theme": "usMechanics", "purpose": "beginner", "scenario": "premarket", "difficulty": 1, "question": "美股盘前（pre market）交易大概在北京时间什么时候？", "options": ["夏令时 16:00–21:30，冬令时 17:00–22:30", "北京时间白天 9:30–15:00", "凌晨 0:00–4:00 全年不变", "美股没有盘前交易"], "answer": [0], "multi": false, "explanation": "盘前在正式开盘前，夏令时北京时间下午 4 点到晚上 9 点半。"},
  {"id": "usMechanics-05", "theme": "usMechanics", "purpose": "beginner", "scenario": "earnings", "difficulty": 1, "question": "美股财报季一般集中在哪些月份？", "options": ["每年 1、4、7、10 月，季报披露期", "只有每年 12 月", "每年 3、6、9、12 月", "美股公司不发财报"], "answer": [0], "multi": false, "explanation": "美股按季度披露，财报季集中在 1、4、7、10 月，波动也最大。"},
  {"id": "usMechanics-06", "theme": "usMechanics", "purpose": "intermediate", "scenario": "holding", "difficulty": 2, "question": "分红除权除息日当天，股价会怎样？", "options": ["保持不变", "开盘参考价下调约分红金额，不是“跌了”", "一定会大涨", "当天停牌"], "answer": [1], "multi": false, "explanation": "分红的钱从股价里切出来，价格下调是除权，不是亏损。"},
  {"id": "usMechanics-07", "theme": "usMechanics", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "做市商（market maker）在美股里主要干什么？", "options": ["操纵股价", "给散户推荐股票", "替上市公司分红", "持续报出买卖价提供流动性，赚取买卖价差"], "answer": [3], "multi": false, "explanation": "做市商是市场的“摊贩”，靠随时有人接盘的价差赚钱。"},
  {"id": "usMechanics-08", "theme": "usMechanics", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "买不起一整股高价股怎么办？", "options": ["只能放弃", "很多券商支持碎股交易，1 美元也能买", "必须借钱买整股", "只能买期权代替"], "answer": [1], "multi": false, "explanation": "碎股交易让小资金也能按金额买高价股，不必攒够一整股。"},
  {"id": "usMechanics-09", "theme": "usMechanics", "purpose": "beginner", "scenario": "any", "difficulty": 2, "question": "美股常规交易时段对应北京时间是？", "options": ["夏令时 21:30–次日 4:00，冬令时 22:30–次日 5:00", "全年 21:30–次日 4:00", "北京时间白天交易", "全年 22:30–次日 5:00"], "answer": [0], "multi": false, "explanation": "美东 9:30–16:00，夏令时比北京晚 12 小时，冬令时晚 13 小时。"},
  {"id": "usMechanics-10", "theme": "usMechanics", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "2026 年 6 月起，美股 PDT（pattern day trader）规则有什么变化？", "options": ["25000 美元门槛取消，改为券商实时风险评估", "门槛提高到 50000 美元", "没有任何变化", "全面禁止日内交易"], "answer": [0], "multi": false, "explanation": "2026年6月起PDT取消，2.5万美元门槛成为历史。"},
  {"id": "usMechanics-11", "theme": "usMechanics", "purpose": "advanced", "scenario": "holding", "difficulty": 3, "question": "纳斯达克“1 美元退市规则”是什么意思？", "options": ["股价跌破 1 美元当天直接退市", "收盘价连续 30 个交易日低于 1 美元会收到警告，再给 180 天整改", "1 美元以下的股票不能买", "退市后股票就一文不值了"], "answer": [1], "multi": false, "explanation": "1 美元规则给的是整改期不是立即死刑，但长期低价多半凶多吉少。"},
  {"id": "usMechanics-12", "theme": "usMechanics", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "关于美股股票代码，哪些说法正确？（多选，共 2 个正确）", "options": ["通常 1–5 个字母，如 AAPL、TSLA", "所有代码都必须是 4 个字母", "同一家公司在不同交易所代码一定相同", "外国股票会带后缀，如 000660.KS"], "answer": [0, 3], "multi": true, "explanation": "美股代码 1–5 个字母自选；跨市场代码常带后缀区分。"},
  {"id": "dividend-01", "theme": "dividend", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "股息（dividend）是什么？", "options": ["公司把利润的一部分现金分给股东", "券商给客户的返佣", "股价上涨的部分", "政府发的补贴"], "answer": [0], "multi": false, "explanation": "股息是公司赚钱后给股东的“分红包”，来自真实利润。"},
  {"id": "dividend-02", "theme": "dividend", "purpose": "beginner", "scenario": "holding", "difficulty": 1, "question": "想拿到这次分红，最晚要在什么时候持有股票？", "options": ["分红到账那天持有就行", "除权除息日前一个交易日收盘时持有", "公告当天买入就行", "任何时候买都行"], "answer": [1], "multi": false, "explanation": "除息日当天买入就赶不上这次分红，得提前一天收盘前持有。"},
  {"id": "dividend-03", "theme": "dividend", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "股价 100 美元、年股息 4 美元，股息率是多少？", "options": ["25%", "0.4%", "4%", "40%"], "answer": [2], "multi": false, "explanation": "股息率=年股息÷股价，4÷100=4%，买价越低股息率越高。"},
  {"id": "dividend-04", "theme": "dividend", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "现金分红和股票分红（送股）的区别是？", "options": ["没有区别", "现金分红真给钱，股票分红只是多发几张“饼”，总市值不变", "股票分红更好，一定能赚钱", "现金分红会让公司破产"], "answer": [1], "multi": false, "explanation": "送股是把一块饼切更多块，你的份额价值当场不变。"},
  {"id": "dividend-05", "theme": "dividend", "purpose": "beginner", "scenario": "any", "difficulty": 1, "question": "公司宣布 10:1 拆股，你持有 1 股 1000 美元，拆完变成？", "options": ["10 股，每股约 100 美元，总市值不变", "1 股 100 美元，亏了 900", "10 股，每股还是 1000 美元，发财了", "股票被没收"], "answer": [0], "multi": false, "explanation": "拆股是“1 张大钞换 10 张小钞”，股数变多、单价变低，总价值不变。"},
  {"id": "dividend-06", "theme": "dividend", "purpose": "intermediate", "scenario": "any", "difficulty": 2, "question": "拆股后公司总市值会怎样？", "options": ["变成原来的两倍", "变成原来的一半", "基本归零", "不变，变的只是股数和单价"], "answer": [3], "multi": false, "explanation": "拆股不创造价值，市值=股数×单价，两边一乘一除刚好抵消。"},
  {"id": "dividend-07", "theme": "dividend", "purpose": "intermediate", "scenario": "holding", "difficulty": 2, "question": "并股（reverse split）通常是什么信号？", "options": ["公司太赚钱了", "股价太低面临退市风险，被迫“合股”保住上市地位", "一定是利好", "和拆股完全一样"], "answer": [1], "multi": false, "explanation": "并股多是低价股的自救，把 10 股并成 1 股凑够 1 美元线。"},
  {"id": "dividend-08", "theme": "dividend", "purpose": "intermediate", "scenario": "earnings", "difficulty": 2, "question": "公司宣布大额股票回购，通常传递什么信号？", "options": ["公司马上要破产", "一定要分红了", "公司觉得自家股票被低估，愿意真金白银买回", "没有任何含义"], "answer": [2], "multi": false, "explanation": "回购注销减少流通股，管理层用现金投票看好自家公司。"},
  {"id": "dividend-09", "theme": "dividend", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "“股息贵族”（Dividend Aristocrats）指什么？", "options": ["分红最多的 10 家公司", "标普 500 中连续 25 年以上每年提高股息的公司", "国王开的公司", "股价最高的公司"], "answer": [1], "multi": false, "explanation": "连续 25 年年年提高分红，穿越过多次危机，现金流极稳。"},
  {"id": "dividend-10", "theme": "dividend", "purpose": "advanced", "scenario": "holding", "difficulty": 3, "question": "一只股票股息率高达 12%，最该警惕什么？", "options": ["分红太多，公司太大方", "可能是股价暴跌把股息率“算”高了，分红随时可能砍", "12% 是正常水平", "赶紧全仓买入"], "answer": [1], "multi": false, "explanation": "股息率=股息÷股价，股价腰斩股息率自动翻倍，高得离谱多半是陷阱。"},
  {"id": "dividend-11", "theme": "dividend", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "中国居民拿美股分红，预扣税怎么算？", "options": ["不用交税", "默认扣 30%，凭中美税收协定填 W-8BEN 可降到 10%", "和美股本地人一样免税", "扣 50%"], "answer": [1], "multi": false, "explanation": "美股股息先预扣再到账，协定待遇要主动填表申请。"},
  {"id": "dividend-12", "theme": "dividend", "purpose": "advanced", "scenario": "any", "difficulty": 3, "question": "DRIP（股息再投资计划）的特点是？（多选，共 2 个正确）", "options": ["分红自动按市价再买入同一只股票，利滚利", "必须手动操作，券商不提供", "很多券商免佣金、支持碎股再投", "再投资的部分不用交税"], "answer": [0, 2], "multi": true, "explanation": "DRIP 让分红自动“生小钱”，但税一分都少不了。"},
];
